### ISSUE TITLE
Deprecate WeakRefStringArray?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaData/WeakRefStrings.jl#36]
`WeakRefStringArray` and `StringArray` serve the same purpose. We need the latter in JuliaDB for performance so should we deprecate the former?

**Comment by quinnj** [comment]
Yes, I need to switch uses of WeakRefStringArray in DataStreams over to StringArray first (or at least before the deprecation is removed)

**Comment by quinnj** [comment]
Packages that still have uses of WeakRefStringArray:
* ODBC
* CSV (tests only)
* DataStreams
* DataFrames (only for DataStreams integration)

I'll work on switching them over to to StringArray

**Comment by quinnj** [comment]
All known uses of WeakRefStringArray have converted to StringArray.
