### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by radioflash** [JuliaData/WeakRefStrings.jl#67]
There was recently some recent discussion on the Julia Slack about package versioning: https://julialang.slack.com/archives/C6M4DQA5P/p1617216478072500

Several people expressed their concerns with how <v1.0 versions are still widespread in the Julia library ecosystem.
These have several issues, compiled in more detail [here](https://github.com/radioflash/julia-library-versioning):

- These packages are bending the Semantic versioning rules, because they *de-facto* define a public API (which SemVer requires to be >=v1.0) 
- <v1.0 packages are unable to cleanly express (non-breaking) feature growth (every change ist either a PATCH release, or "breaking")
- The transition to v1.0 is necessarily a breaking change, which often does not make any sense

Having been affected by related versioning problems before, I'm now trying to push packages (especially widely used ones) toward v1.0.

I'm specifically posting here because this is a direct dependency of CSV.jl, which I'd love to have at v1.0 also!

**Comment by quinnj** [comment]
Yes, I'm fine registering a 1.0 release the next time we need to do a release.
