### ISSUE TITLE
Incorrect declaration of julia compatibility

### ISSUE THREAD

**Issue by piever** [JuliaData/WeakRefStrings.jl#72]
I've noticed in StructArray's CI that even though WeakRefStrings claims julia 1.0 compatibility, it does not work on 1.0, because of `Base.__unsafe_string!`, see [CI](https://github.com/JuliaArrays/StructArrays.jl/runs/2896018971?check_suite_focus=true#step:6:40).

Would it be feasible to update the compat bounds in the Project file here to julia 1.3 (which is the one that is tested) and update the released version on the General registry to only be valid from julia 1.3 onwards?

Otherwise this becomes a bit tricky as a test dependency on StructArrays (which still supports julia 1.0).

**Comment by quinnj** [comment]
Ok, should be fixed now

**Comment by piever** [comment]
Thanks! For the package to work out of the box on julia 1.0 we should also somehow change the 1.0 release in General, because that is still the one installed by default. I think this should be done as a PR to General that updates the compatibility info, but I'm not too sure how. It's probably a matter of changing [this line](https://github.com/JuliaRegistries/General/blob/master/W/WeakRefStrings/Compat.toml#L17).
