### ISSUE TITLE
shorter name for InlineString[X]

### ISSUE THREAD

**Issue by bkamins** [JuliaData/WeakRefStrings.jl#85]
`InlineString[X]` is a long name. It does not display very nicely.

My proposal would be:
* rename `InlineString1` to `String1`
* make `InlineString1` an alias pointing to `String1` (so that the change is not breaking)

CC @nalimilan @quinnj

**Comment by nalimilan** [comment]
To add some arguments: the printing of `InlineString[X]` in the header of data frame columns is quite bad as the name is longer than the contents of the column (which are short strings by definition). `String[X]` would be shorter, and I like the parallel with `Int[X]` and such.

**Comment by quinnj** [comment]
Yeah, that all sounds good to me. Someone mind making a PR?
